# Generated by Django 4.0.4 on 2022-05-01 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('season_number', models.IntegerField(null=True)),
                ('episode_number', models.IntegerField(null=True)),
                ('said_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes_api.character')),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes_api.tvshow')),
            ],
        ),
    ]
